// Generated by binpac_quickstart

#include "NOISE.h"

#include "Reporter.h"

#include "events.bif.h"

using namespace analyzer::NOISE;

NOISE_Analyzer::NOISE_Analyzer(Connection* c)

: analyzer::Analyzer("NOISE", c)

	{
	interp = new binpac::NOISE::NOISE_Conn(this);
	
	}

NOISE_Analyzer::~NOISE_Analyzer()
	{
	delete interp;
	}

void NOISE_Analyzer::Done()
	{
	
	Analyzer::Done();
	
	}

void NOISE_Analyzer::DeliverPacket(int len, const u_char* data,
	 			  bool orig, uint64_t seq, const IP_Hdr* ip, int caplen)
	{
	Analyzer::DeliverPacket(len, data, orig, seq, ip, caplen);

	try
		{
		interp->NewData(orig, data, data + len);
		}
	catch ( const binpac::Exception& e )
		{
		ProtocolViolation(fmt("Binpac exception: %s", e.c_msg()));
		}
	}
