// Generated by binpac_quickstart

#include "NOISE.h"
#include "plugin/Plugin.h"
#include "analyzer/Component.h"

#include "NOISE.h"

namespace plugin {
namespace ZEEK_NOISE {

class Plugin : public plugin::Plugin {
public:
	plugin::Configuration Configure()
		{
		AddComponent(new ::analyzer::Component("NOISE",
		             ::analyzer::NOISE::NOISE_Analyzer::InstantiateAnalyzer));

		plugin::Configuration config;
		config.name = "ZEEK::NOISE";
		config.description = "Noise analyzer";
		config.version.major = 0;
		config.version.minor = 1;
		config.version.patch = 0;
		return config;
		}
} plugin;

}
}